<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test Suite_DDT</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>651a2b74-86cf-48fe-a62e-c8d043b45bcf</testSuiteGuid>
   <testCaseLink>
      <guid>2fd77eed-6351-4c68-9eb9-f7a85519c3dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Openweb_dungbien</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7c2db586-eb36-4511-895f-3fa8843021af</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>162d2271-21c5-4239-b32a-159d55a45ad0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b05c5e78-9e9d-479f-8923-9707517bc9cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02d47ad4-770e-47f8-860b-aafae37d4367</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23adc1cf-9586-497c-b208-1281f8316f1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7c2db586-eb36-4511-895f-3fa8843021af</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>88873ed9-2c68-46a5-b4a9-8a8e97a3af2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7c2db586-eb36-4511-895f-3fa8843021af</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>passw</value>
         <variableId>1856b3ac-ae95-47e0-98c3-debbdeb2d9b5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
